---
train:
  params:
    batch_size: 256
    epoch: 20
    lr: 0.001
    decay: 0.1
    decay_step: 75000
    loss: MSELoss
  save:
    save_path: "/home/cyh/GazeBenchmark/exp/Implementation/Itracker"
    model_name: Itracker
    step: 5
  data:
    image: "/home/cyh/GazeDataset20200519/GazePoint/GazeCapture/Image"
    label: "/home/cyh/GazeDataset20200519/GazePoint/GazeCapture/Label/train"
  pretrains: "None"
test:
   load:
      begin_step: 5
      end_step: 20
      steps: 5
      load_path: "/home/cyh/GazeBenchmark/exp/Implementation/Itracker"
      model_name: Itracker
   data:
      image: "/home/cyh/GazeDataset20200519/GazePoint/GazeCapture/Image"
      label: "/home/cyh/GazeDataset20200519/GazePoint/GazeCapture/Label/test"
reader: reader_gc
